export const validWords = [
  "abang", "absen", "adat", "adops", "aduan", "agung", "ajang",
  "akar", "akbar", "akrab", "alamat", "alami", "alang",
  "amati", "amben", "ambik", "ambur", "amino", "ampas",
  "amper", "ampuh", "amung", "anang", "ancas", "andam",
  "angan", "anggap", "angga", "angin", "angkat",
  "angku", "angon", "angsar", "angkat", "antap",
  "antem", "antik", "anton", "antri", "anyam",
  "apung", "arah", "arang", "arena", "argot",
  "aries", "asbes", "asing", "aspek", "asli",
  "asong", "aspek", "aturan", "aurat", "autis",
  "avtur", "awam", "awan", "awet",
  "bagan", "bagas", "bagus", "bahak", "bahas",
  "bahut", "bajak", "bakap", "bakri", "balai",
  "balap", "balas", "balik", "balok", "bambu",
  "banal", "banco", "banir", "banua", "bantu",
  "bapak", "barat", "baris", "baron", "batal",
  "bater", "batin", "batok", "batun", "batur",
  "bawah", "bawuk", "bayam", "bayar",
  "beban", "bebek", "bedah", "begal", "bekal",
  "belah", "belas", "belit", "belok", "belut",
  "benar", "benih", "benur", "benua", "berai",
  "berak", "berat", "beres", "beril", "besik",
  "betah", "beton", "betot",
  "biang", "biaya", "bibir", "bidak", "bidik",
  "bilik", "bimah", "bina", "binom", "biota",
  "bisai", "bisik", "bisul", "bison",
  "bogel", "bogor", "bohai", "bokar", "boksu",
  "bolog", "bolos", "bolot", "bongs", "borok",
  "bubur", "budak", "budek", "bujet",
  "bujur", "bulan", "bumbu", "bumun",
  "cabai", "cabul", "cadar", "cagak", "cair", 
  "cakar", "cakra", "candu", "capek", "capai",
  "cebur", "ceder", "cekak", "cekam", "cekik",
  "celah", "celak", "celup", "cenak", "cetak",
  "cider", "cicit", "cilap", "cinta",
  "daear", "dalam", "damar", "damai", "dangau",
  "datar", "datuk", "dayah",
  "debat", "dewan", "dewasa", "delta", "denda",
  "desak", "desa", "dingin", "disko", "dikit",
  "domba", "dosen", "dukac", "dukun",
  "edisi", "efekt", "ekang", "ekran", "eksek",
  "elips", "elite", "email", "empuk",
  "fajar", "fakta", "fatal", "fitur", "fokus",
  "garam", "gadur", "gagal", "gagas", "gajah",
  "gajih", "galah", "galau", "gamak",
  "gambar", "ganda", "gandi", "ganja", "garis",
  "gatal", "gerak", "geram", "gerap", "gerut",
  "giant", "gigit", "ginda", "gitar",
  "habis", "hadap", "hadir", "hafal", "hakim",
  "halal", "halau", "hamil", "hamik",
  "hampa", "hapus", "haram", "harim", "harus",
  "ibing", "ideat", "iklan", "impor", "indah",
  "indik", "indra", "infak",
  "jabat", "jadi", "jadah", "jajar", "jaksa",
  "jalan", "jalur", "jamin", "jamur", "janda",
  "janur", "jarak", "jatah",
  "kabar", "kabil", "kabul", "kacau", "kader",
  "kadet", "kafir", "kagum", "kalah", "kalem",
  "kalut", "kamal", "kamus", "kanal", "kanda",
  "kangs", "kanon", "kantin",
  "kapal", "kapok", "kapal", "kapan", "karet",
  "kasar", "kasih", "kasus", "katek",
  "kawal", "kaya", "kayuh", "kebal",
  "laban", "label", "labor", "laden", "lagak",
  "lagun", "lahir", "lajur", "lakar",
  "lambat", "lamun", "lapis", "lapor", "laras",
  "larut", "lebar", "lebih", "lebuh", "lecet",
  "legal", "legit", "lensa", "lirik", "lisah",
  "lunas", "luhur", 
  "macan", "macet", "madam", "mager", "maghr",
  "mahal", "mahir", "majas", "majel",
  "major", "makam", "makna",
  "malam", "malas", "malik", "mampu", "mandi",
  "manis", "mangu", "mantap",
  "mapan", "marah", "massa", "mater", "matra",
  "mazur",
  "nadar", "nadir", "nafas", "naik", "nalar",
  "nalur", "nanda",
  "oasis", "obrol", "obyek", "oglak", "oktap",
  "ombak",
  "pagar", "paham", "pajak", "paket", "paksa",
  "palah", "palau", "pamer", "panas",
  "pandu", "papan", "lapor", "parah", "paris",
  "pasar", "pasif", "pasok", "patuh",
  "pecah", "pecat", "pedal", "pedas", "pedes",
  "pekan", "peluk", "pelit",
  "qasar", "quran",
  "radar", "radik", "ragam", "ragas", "rahas",
  "rahim", "rajah", "rajut", "rakai",
  "ramal", "ramai", "ramus", "ranah", "rancu",
  "rapat", "rasio", "rasul",
  "sabar", "sabit", "sadar", "saham", "sahih",
  "sakat", "salak", "salat", "salah",
  "samar", "samba", "sampai", "sampo",
  "sandi", "saran", "sasar",
  "tabel", "tadar", "tafas", "tahan", "tajar",
  "takut", "talak", "talun", "tamak",
  "tamat", "tanam", "tanah", "tanda", "tandu",
  "tango", "tango", "tanya",
  "ubang", "ubudi", "udara", "udeng", "udung",
  "ujung", "ukasi", "ukran",
  "ulang", "ultra",
  "vapor", "varia", "venus", "video",
  "wabah", "wafat", "wagon", "wahid", "wajar",
  "waktu", "warna", "waris", "waruk",
  "xenon",
  "yatim", "yuana",
  "zakat", "zaman", "zatku", "zirah"
]
